version: "3.1"

services:
  nginx:
    image: nginx:latest
    restart: always
    container_name: contabil_web
    environment:
      TZ: "America/Sao_Paulo"
    ports:
      - "8008:8008"
    volumes:
      - ./app:/app
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - django
    networks:
      - main

  django:
    build: .
    container_name: contabil_app
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
    env_file:
      - ./env/development.env
    command: >
      /bin/sh -c 'python manage.py makemigrations &&
                  python manage.py migrate &&
                  python manage.py collectstatic --noinput &&
                  python manage.py compress --force &&
                  python manage.py sync_roles --reset_user_permissions &&
                  gunicorn contabil.wsgi -b "0.0.0.0:8008"'
    volumes:
      - ./app:/usr/src/app
      - ./app/db.sqlite3:/usr/src/app/db.sqlite3
      - ./backups:/var/backups
    expose:
      - "8008"
    networks:
      - main

networks:
  main:
