version: '3.1'

services:
  nginx:
    image: nginx:latest
    restart: always
    container_name: afinco_web
    environment:
      TZ: 'America/Sao_Paulo'
    ports:
      - '8008:8008'
    volumes:
      - ./app:/app
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - django
    networks:
      - main

  db:
    image: mariadb:10-bionic
    restart: always
    container_name: afinco_db
    environment:
      TZ: 'America/Sao_Paulo'
    env_file:
      - ./env/production.env
    volumes:
      - db_storage:/var/lib/mysql
    ports:
      - '3308:3306'
    networks:
      - main

  django:
    build: .
    container_name: afinco_app
    restart: always
    environment:
      TZ: 'America/Sao_Paulo'
    env_file:
      - ./env/production.env
    command: >
      /bin/sh -c 'python manage.py makemigrations &&
                  python manage.py migrate &&
                  python manage.py collectstatic --noinput -c &&
                  python manage.py compress --force &&
                  python manage.py sync_roles --reset_user_permissions &&
                  gunicorn contabil.wsgi -b "0.0.0.0:8008"'
    volumes:
      - ./app:/usr/src/app
      - ./backups:/var/backups
    expose:
      - '8008'
    depends_on:
      - db
    networks:
      - main

volumes:
  db_storage:

networks:
  main:
